# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogicalDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('connected', models.BooleanField(default=False)),
                ('device_name', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=30)),
                ('device_status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='logicaldevice',
            name='physical_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PhysicalDevice'),
        ),
    ]
